### PR TITLE
React google maps

### LINKED ISSUE #75: Update react-google-maps
Currently, we're using `react-google-maps@^4.11.0`. We need to update [this package](https://tomchentw.github.io/react-google-maps/). 

Looking at the [changelog](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md), it seems we need to fix some breaking changes.
A major change I could find is [here](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md#breaking-changes-2), though you can go ahead and find other breaking changes as well.

We're using this package in [ReactiveMaps](https://github.com/appbaseio/reactivemaps/blob/dev/app/actuators/ReactiveMap.js) actuator.

Workflow breakdown:
- [x] View [changelog](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md) and find all breaking changes from `4.11.0` to latest.
- [x] Update react-google-maps package
- [x] Refactor [ReactiveMaps](https://github.com/appbaseio/reactivemaps/blob/dev/app/actuators/ReactiveMap.js) code
- [x] Test by using storybook example `npm run storybook`
- [ ] Send PR. :tada:

### PR DESCRIPTION
**Pull request by vcapretz**
it should update the package version to latest, some breaking changes
need to be fixed, this commit starts to fix a few of them

closes #75

### CODE REVIEW

**Comment by dhruvdutt** [comment]
This should resolve [#231](https://github.com/appbaseio/reactivebase/issues/231)

**Comment by vcapretz** [comment]
I just removed the file @dhruvdutt!

**Comment by metagrover** [comment]
Hi @vcapretz, were you able to get the map component to work in the storybook or examples. I just verified it, it is failing to load.

**Comment by metagrover** [comment]
Closing this PR due to inactivity and non-functional code.

You may check the [working code here](https://github.com/appbaseio/reactivemaps/commit/a4ca7440a26f87d0877add8c8da4058948897e2c).

**Pull request closed without merging**
